// Autogenerated from Pigeon (v0.1.23), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "messages.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString*, id>* wrapResult(NSDictionary *result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}

@interface GALTrackerBoolValue ()
+(GALTrackerBoolValue*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface GALTrackerIntValue ()
+(GALTrackerIntValue*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface GALHitBuilderMessage ()
+(GALHitBuilderMessage*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface GALStringValue ()
+(GALStringValue*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface GALTrackerStringValue ()
+(GALTrackerStringValue*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface GALTrackerSetValue ()
+(GALTrackerSetValue*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface GALTrackerDoubleValue ()
+(GALTrackerDoubleValue*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface GALIntValue ()
+(GALIntValue*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end

@implementation GALTrackerBoolValue
+(GALTrackerBoolValue*)fromMap:(NSDictionary*)dict {
  GALTrackerBoolValue* result = [[GALTrackerBoolValue alloc] init];
  result.trackerId = dict[@"trackerId"];
  if ((NSNull *)result.trackerId == [NSNull null]) {
    result.trackerId = nil;
  }
  result.value = dict[@"value"];
  if ((NSNull *)result.value == [NSNull null]) {
    result.value = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.trackerId ? self.trackerId : [NSNull null]), @"trackerId", (self.value ? self.value : [NSNull null]), @"value", nil];
}
@end

@implementation GALTrackerIntValue
+(GALTrackerIntValue*)fromMap:(NSDictionary*)dict {
  GALTrackerIntValue* result = [[GALTrackerIntValue alloc] init];
  result.trackerId = dict[@"trackerId"];
  if ((NSNull *)result.trackerId == [NSNull null]) {
    result.trackerId = nil;
  }
  result.value = dict[@"value"];
  if ((NSNull *)result.value == [NSNull null]) {
    result.value = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.trackerId ? self.trackerId : [NSNull null]), @"trackerId", (self.value ? self.value : [NSNull null]), @"value", nil];
}
@end

@implementation GALHitBuilderMessage
+(GALHitBuilderMessage*)fromMap:(NSDictionary*)dict {
  GALHitBuilderMessage* result = [[GALHitBuilderMessage alloc] init];
  result.trackerId = dict[@"trackerId"];
  if ((NSNull *)result.trackerId == [NSNull null]) {
    result.trackerId = nil;
  }
  result.data = dict[@"data"];
  if ((NSNull *)result.data == [NSNull null]) {
    result.data = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.trackerId ? self.trackerId : [NSNull null]), @"trackerId", (self.data ? self.data : [NSNull null]), @"data", nil];
}
@end

@implementation GALStringValue
+(GALStringValue*)fromMap:(NSDictionary*)dict {
  GALStringValue* result = [[GALStringValue alloc] init];
  result.value = dict[@"value"];
  if ((NSNull *)result.value == [NSNull null]) {
    result.value = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.value ? self.value : [NSNull null]), @"value", nil];
}
@end

@implementation GALTrackerStringValue
+(GALTrackerStringValue*)fromMap:(NSDictionary*)dict {
  GALTrackerStringValue* result = [[GALTrackerStringValue alloc] init];
  result.trackerId = dict[@"trackerId"];
  if ((NSNull *)result.trackerId == [NSNull null]) {
    result.trackerId = nil;
  }
  result.value = dict[@"value"];
  if ((NSNull *)result.value == [NSNull null]) {
    result.value = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.trackerId ? self.trackerId : [NSNull null]), @"trackerId", (self.value ? self.value : [NSNull null]), @"value", nil];
}
@end

@implementation GALTrackerSetValue
+(GALTrackerSetValue*)fromMap:(NSDictionary*)dict {
  GALTrackerSetValue* result = [[GALTrackerSetValue alloc] init];
  result.trackerId = dict[@"trackerId"];
  if ((NSNull *)result.trackerId == [NSNull null]) {
    result.trackerId = nil;
  }
  result.key = dict[@"key"];
  if ((NSNull *)result.key == [NSNull null]) {
    result.key = nil;
  }
  result.value = dict[@"value"];
  if ((NSNull *)result.value == [NSNull null]) {
    result.value = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.trackerId ? self.trackerId : [NSNull null]), @"trackerId", (self.key ? self.key : [NSNull null]), @"key", (self.value ? self.value : [NSNull null]), @"value", nil];
}
@end

@implementation GALTrackerDoubleValue
+(GALTrackerDoubleValue*)fromMap:(NSDictionary*)dict {
  GALTrackerDoubleValue* result = [[GALTrackerDoubleValue alloc] init];
  result.trackerId = dict[@"trackerId"];
  if ((NSNull *)result.trackerId == [NSNull null]) {
    result.trackerId = nil;
  }
  result.value = dict[@"value"];
  if ((NSNull *)result.value == [NSNull null]) {
    result.value = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.trackerId ? self.trackerId : [NSNull null]), @"trackerId", (self.value ? self.value : [NSNull null]), @"value", nil];
}
@end

@implementation GALIntValue
+(GALIntValue*)fromMap:(NSDictionary*)dict {
  GALIntValue* result = [[GALIntValue alloc] init];
  result.value = dict[@"value"];
  if ((NSNull *)result.value == [NSNull null]) {
    result.value = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.value ? self.value : [NSNull null]), @"value", nil];
}
@end

void GALTrackerApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<GALTrackerApi> api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.enableExceptionReporting"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerBoolValue *input = [GALTrackerBoolValue fromMap:message];
        FlutterError *error;
        [api enableExceptionReporting:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setSessionTimeout"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerIntValue *input = [GALTrackerIntValue fromMap:message];
        FlutterError *error;
        [api setSessionTimeout:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.enableAutoActivityTracking"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerBoolValue *input = [GALTrackerBoolValue fromMap:message];
        FlutterError *error;
        [api enableAutoActivityTracking:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.send"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALHitBuilderMessage *input = [GALHitBuilderMessage fromMap:message];
        FlutterError *error;
        [api send:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.get"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerStringValue *input = [GALTrackerStringValue fromMap:message];
        FlutterError *error;
        GALStringValue *output = [api get:input error:&error];
        callback(wrapResult([output toMap], error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.set"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerSetValue *input = [GALTrackerSetValue fromMap:message];
        FlutterError *error;
        [api set:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setSampleRate"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerDoubleValue *input = [GALTrackerDoubleValue fromMap:message];
        FlutterError *error;
        [api setSampleRate:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setUseSecure"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerBoolValue *input = [GALTrackerBoolValue fromMap:message];
        FlutterError *error;
        [api setUseSecure:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setScreenName"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerStringValue *input = [GALTrackerStringValue fromMap:message];
        FlutterError *error;
        [api setScreenName:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setLocation"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerStringValue *input = [GALTrackerStringValue fromMap:message];
        FlutterError *error;
        [api setLocation:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setReferrer"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerStringValue *input = [GALTrackerStringValue fromMap:message];
        FlutterError *error;
        [api setReferrer:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setPage"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerStringValue *input = [GALTrackerStringValue fromMap:message];
        FlutterError *error;
        [api setPage:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setHostname"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerStringValue *input = [GALTrackerStringValue fromMap:message];
        FlutterError *error;
        [api setHostname:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setTitle"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerStringValue *input = [GALTrackerStringValue fromMap:message];
        FlutterError *error;
        [api setTitle:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setLanguage"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerStringValue *input = [GALTrackerStringValue fromMap:message];
        FlutterError *error;
        [api setLanguage:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setEncoding"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerStringValue *input = [GALTrackerStringValue fromMap:message];
        FlutterError *error;
        [api setEncoding:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setScreenColors"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerStringValue *input = [GALTrackerStringValue fromMap:message];
        FlutterError *error;
        [api setScreenColors:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setScreenResolution"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALIntValue *input = [GALIntValue fromMap:message];
        FlutterError *error;
        [api setScreenResolution:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setViewportSize"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerStringValue *input = [GALTrackerStringValue fromMap:message];
        FlutterError *error;
        [api setViewportSize:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setClientId"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerStringValue *input = [GALTrackerStringValue fromMap:message];
        FlutterError *error;
        [api setClientId:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setAppName"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerStringValue *input = [GALTrackerStringValue fromMap:message];
        FlutterError *error;
        [api setAppName:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setAppId"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerStringValue *input = [GALTrackerStringValue fromMap:message];
        FlutterError *error;
        [api setAppId:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setAppInstallerId"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerStringValue *input = [GALTrackerStringValue fromMap:message];
        FlutterError *error;
        [api setAppInstallerId:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setAppVersion"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerStringValue *input = [GALTrackerStringValue fromMap:message];
        FlutterError *error;
        [api setAppVersion:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.setAnonymizeIp"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerBoolValue *input = [GALTrackerBoolValue fromMap:message];
        FlutterError *error;
        [api setAnonymizeIp:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.TrackerApi.enableAdvertisingIdCollection"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALTrackerBoolValue *input = [GALTrackerBoolValue fromMap:message];
        FlutterError *error;
        [api enableAdvertisingIdCollection:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
void GALGoogleAnalyticsApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<GALGoogleAnalyticsApi> api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.GoogleAnalyticsApi.getInstance"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api getInstance:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.GoogleAnalyticsApi.newTracker"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        GALStringValue *input = [GALStringValue fromMap:message];
        FlutterError *error;
        GALIntValue *output = [api newTracker:input error:&error];
        callback(wrapResult([output toMap], error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
