// Autogenerated from Pigeon (v0.1.23), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class GALTrackerBoolValue;
@class GALTrackerIntValue;
@class GALHitBuilderMessage;
@class GALTrackerGetValue;
@class GALTrackerStringValue;
@class GALTrackerSetValue;
@class GALTrackerDoubleValue;
@class GALTrackerSetScreenResolutionValue;
@class GALTrackerGetClientIdValue;
@class GALTrackerIdValue;
@class GALGABool;
@class GALGAInt;
@class GALTrackerId;
@class GALTrackingId;

@interface GALTrackerBoolValue : NSObject
@property(nonatomic, strong, nullable) NSNumber * trackerId;
@property(nonatomic, strong, nullable) NSNumber * value;
@end

@interface GALTrackerIntValue : NSObject
@property(nonatomic, strong, nullable) NSNumber * trackerId;
@property(nonatomic, strong, nullable) NSNumber * value;
@end

@interface GALHitBuilderMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * trackerId;
@property(nonatomic, copy, nullable) NSString * data;
@end

@interface GALTrackerGetValue : NSObject
@property(nonatomic, copy, nullable) NSString * value;
@end

@interface GALTrackerStringValue : NSObject
@property(nonatomic, strong, nullable) NSNumber * trackerId;
@property(nonatomic, copy, nullable) NSString * value;
@end

@interface GALTrackerSetValue : NSObject
@property(nonatomic, strong, nullable) NSNumber * trackerId;
@property(nonatomic, copy, nullable) NSString * key;
@property(nonatomic, copy, nullable) NSString * value;
@end

@interface GALTrackerDoubleValue : NSObject
@property(nonatomic, strong, nullable) NSNumber * trackerId;
@property(nonatomic, strong, nullable) NSNumber * value;
@end

@interface GALTrackerSetScreenResolutionValue : NSObject
@property(nonatomic, strong, nullable) NSNumber * trackerId;
@property(nonatomic, strong, nullable) NSNumber * value1;
@property(nonatomic, strong, nullable) NSNumber * value2;
@end

@interface GALTrackerGetClientIdValue : NSObject
@property(nonatomic, copy, nullable) NSString * value;
@end

@interface GALTrackerIdValue : NSObject
@property(nonatomic, strong, nullable) NSNumber * trackerId;
@end

@interface GALGABool : NSObject
@property(nonatomic, strong, nullable) NSNumber * value;
@end

@interface GALGAInt : NSObject
@property(nonatomic, strong, nullable) NSNumber * value;
@end

@interface GALTrackerId : NSObject
@property(nonatomic, strong, nullable) NSNumber * trackerId;
@end

@interface GALTrackingId : NSObject
@property(nonatomic, copy, nullable) NSString * trackingId;
@end

@protocol GALTrackerApi
-(void)enableExceptionReporting:(GALTrackerBoolValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setSessionTimeout:(GALTrackerIntValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)enableAutoActivityTracking:(GALTrackerBoolValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)send:(GALHitBuilderMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(nullable GALTrackerGetValue *)get:(GALTrackerStringValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)set:(GALTrackerSetValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setSampleRate:(GALTrackerDoubleValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setUseSecure:(GALTrackerBoolValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setScreenName:(GALTrackerStringValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setLocation:(GALTrackerStringValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setReferrer:(GALTrackerStringValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setPage:(GALTrackerStringValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setHostname:(GALTrackerStringValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setTitle:(GALTrackerStringValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setLanguage:(GALTrackerStringValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setEncoding:(GALTrackerStringValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setScreenColors:(GALTrackerStringValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setScreenResolution:(GALTrackerSetScreenResolutionValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setViewportSize:(GALTrackerStringValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(nullable GALTrackerGetClientIdValue *)getClientId:(GALTrackerIdValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setClientId:(GALTrackerStringValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setAppName:(GALTrackerStringValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setAppId:(GALTrackerStringValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setAppInstallerId:(GALTrackerStringValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setAppVersion:(GALTrackerStringValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setAnonymizeIp:(GALTrackerBoolValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)enableAdvertisingIdCollection:(GALTrackerBoolValue*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void GALTrackerApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<GALTrackerApi> _Nullable api);

@protocol GALGoogleAnalyticsApi
-(void)getInstance:(FlutterError *_Nullable *_Nonnull)error;
-(void)setLogLevelVerbose:(FlutterError *_Nullable *_Nonnull)error;
-(void)setDryRun:(GALGABool*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(nullable GALGABool *)isDryRunEnabled:(FlutterError *_Nullable *_Nonnull)error;
-(void)setAppOptOut:(GALGABool*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(nullable GALGABool *)getAppOptOut:(FlutterError *_Nullable *_Nonnull)error;
-(void)setLocalDispatchPeriod:(GALGAInt*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(nullable GALTrackerId *)newTracker:(GALTrackingId*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void GALGoogleAnalyticsApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<GALGoogleAnalyticsApi> _Nullable api);

NS_ASSUME_NONNULL_END
