// Autogenerated from Pigeon (v0.1.23), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package cz.vps4u.google_analytics_legacy;

import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.StandardMessageCodec;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class Messages {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class TrackerBoolValue {
    private Long trackerId;
    public Long getTrackerId() { return trackerId; }
    public void setTrackerId(Long setterArg) { this.trackerId = setterArg; }

    private Boolean value;
    public Boolean getValue() { return value; }
    public void setValue(Boolean setterArg) { this.value = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("trackerId", trackerId);
      toMapResult.put("value", value);
      return toMapResult;
    }
    static TrackerBoolValue fromMap(Map<String, Object> map) {
      TrackerBoolValue fromMapResult = new TrackerBoolValue();
      Object trackerId = map.get("trackerId");
      fromMapResult.trackerId = (trackerId == null) ? null : ((trackerId instanceof Integer) ? (Integer)trackerId : (Long)trackerId);
      Object value = map.get("value");
      fromMapResult.value = (Boolean)value;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class TrackerIntValue {
    private Long trackerId;
    public Long getTrackerId() { return trackerId; }
    public void setTrackerId(Long setterArg) { this.trackerId = setterArg; }

    private Long value;
    public Long getValue() { return value; }
    public void setValue(Long setterArg) { this.value = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("trackerId", trackerId);
      toMapResult.put("value", value);
      return toMapResult;
    }
    static TrackerIntValue fromMap(Map<String, Object> map) {
      TrackerIntValue fromMapResult = new TrackerIntValue();
      Object trackerId = map.get("trackerId");
      fromMapResult.trackerId = (trackerId == null) ? null : ((trackerId instanceof Integer) ? (Integer)trackerId : (Long)trackerId);
      Object value = map.get("value");
      fromMapResult.value = (value == null) ? null : ((value instanceof Integer) ? (Integer)value : (Long)value);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class HitBuilderMessage {
    private Long trackerId;
    public Long getTrackerId() { return trackerId; }
    public void setTrackerId(Long setterArg) { this.trackerId = setterArg; }

    private String data;
    public String getData() { return data; }
    public void setData(String setterArg) { this.data = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("trackerId", trackerId);
      toMapResult.put("data", data);
      return toMapResult;
    }
    static HitBuilderMessage fromMap(Map<String, Object> map) {
      HitBuilderMessage fromMapResult = new HitBuilderMessage();
      Object trackerId = map.get("trackerId");
      fromMapResult.trackerId = (trackerId == null) ? null : ((trackerId instanceof Integer) ? (Integer)trackerId : (Long)trackerId);
      Object data = map.get("data");
      fromMapResult.data = (String)data;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class TrackerGetValue {
    private String value;
    public String getValue() { return value; }
    public void setValue(String setterArg) { this.value = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("value", value);
      return toMapResult;
    }
    static TrackerGetValue fromMap(Map<String, Object> map) {
      TrackerGetValue fromMapResult = new TrackerGetValue();
      Object value = map.get("value");
      fromMapResult.value = (String)value;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class TrackerStringValue {
    private Long trackerId;
    public Long getTrackerId() { return trackerId; }
    public void setTrackerId(Long setterArg) { this.trackerId = setterArg; }

    private String value;
    public String getValue() { return value; }
    public void setValue(String setterArg) { this.value = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("trackerId", trackerId);
      toMapResult.put("value", value);
      return toMapResult;
    }
    static TrackerStringValue fromMap(Map<String, Object> map) {
      TrackerStringValue fromMapResult = new TrackerStringValue();
      Object trackerId = map.get("trackerId");
      fromMapResult.trackerId = (trackerId == null) ? null : ((trackerId instanceof Integer) ? (Integer)trackerId : (Long)trackerId);
      Object value = map.get("value");
      fromMapResult.value = (String)value;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class TrackerSetValue {
    private Long trackerId;
    public Long getTrackerId() { return trackerId; }
    public void setTrackerId(Long setterArg) { this.trackerId = setterArg; }

    private String key;
    public String getKey() { return key; }
    public void setKey(String setterArg) { this.key = setterArg; }

    private String value;
    public String getValue() { return value; }
    public void setValue(String setterArg) { this.value = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("trackerId", trackerId);
      toMapResult.put("key", key);
      toMapResult.put("value", value);
      return toMapResult;
    }
    static TrackerSetValue fromMap(Map<String, Object> map) {
      TrackerSetValue fromMapResult = new TrackerSetValue();
      Object trackerId = map.get("trackerId");
      fromMapResult.trackerId = (trackerId == null) ? null : ((trackerId instanceof Integer) ? (Integer)trackerId : (Long)trackerId);
      Object key = map.get("key");
      fromMapResult.key = (String)key;
      Object value = map.get("value");
      fromMapResult.value = (String)value;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class TrackerDoubleValue {
    private Long trackerId;
    public Long getTrackerId() { return trackerId; }
    public void setTrackerId(Long setterArg) { this.trackerId = setterArg; }

    private Double value;
    public Double getValue() { return value; }
    public void setValue(Double setterArg) { this.value = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("trackerId", trackerId);
      toMapResult.put("value", value);
      return toMapResult;
    }
    static TrackerDoubleValue fromMap(Map<String, Object> map) {
      TrackerDoubleValue fromMapResult = new TrackerDoubleValue();
      Object trackerId = map.get("trackerId");
      fromMapResult.trackerId = (trackerId == null) ? null : ((trackerId instanceof Integer) ? (Integer)trackerId : (Long)trackerId);
      Object value = map.get("value");
      fromMapResult.value = (Double)value;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class TrackerSetScreenResolutionValue {
    private Long trackerId;
    public Long getTrackerId() { return trackerId; }
    public void setTrackerId(Long setterArg) { this.trackerId = setterArg; }

    private Long value1;
    public Long getValue1() { return value1; }
    public void setValue1(Long setterArg) { this.value1 = setterArg; }

    private Long value2;
    public Long getValue2() { return value2; }
    public void setValue2(Long setterArg) { this.value2 = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("trackerId", trackerId);
      toMapResult.put("value1", value1);
      toMapResult.put("value2", value2);
      return toMapResult;
    }
    static TrackerSetScreenResolutionValue fromMap(Map<String, Object> map) {
      TrackerSetScreenResolutionValue fromMapResult = new TrackerSetScreenResolutionValue();
      Object trackerId = map.get("trackerId");
      fromMapResult.trackerId = (trackerId == null) ? null : ((trackerId instanceof Integer) ? (Integer)trackerId : (Long)trackerId);
      Object value1 = map.get("value1");
      fromMapResult.value1 = (value1 == null) ? null : ((value1 instanceof Integer) ? (Integer)value1 : (Long)value1);
      Object value2 = map.get("value2");
      fromMapResult.value2 = (value2 == null) ? null : ((value2 instanceof Integer) ? (Integer)value2 : (Long)value2);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class TrackerGetClientIdValue {
    private String value;
    public String getValue() { return value; }
    public void setValue(String setterArg) { this.value = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("value", value);
      return toMapResult;
    }
    static TrackerGetClientIdValue fromMap(Map<String, Object> map) {
      TrackerGetClientIdValue fromMapResult = new TrackerGetClientIdValue();
      Object value = map.get("value");
      fromMapResult.value = (String)value;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class TrackerIdValue {
    private Long trackerId;
    public Long getTrackerId() { return trackerId; }
    public void setTrackerId(Long setterArg) { this.trackerId = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("trackerId", trackerId);
      return toMapResult;
    }
    static TrackerIdValue fromMap(Map<String, Object> map) {
      TrackerIdValue fromMapResult = new TrackerIdValue();
      Object trackerId = map.get("trackerId");
      fromMapResult.trackerId = (trackerId == null) ? null : ((trackerId instanceof Integer) ? (Integer)trackerId : (Long)trackerId);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class GABool {
    private Boolean value;
    public Boolean getValue() { return value; }
    public void setValue(Boolean setterArg) { this.value = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("value", value);
      return toMapResult;
    }
    static GABool fromMap(Map<String, Object> map) {
      GABool fromMapResult = new GABool();
      Object value = map.get("value");
      fromMapResult.value = (Boolean)value;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class GAInt {
    private Long value;
    public Long getValue() { return value; }
    public void setValue(Long setterArg) { this.value = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("value", value);
      return toMapResult;
    }
    static GAInt fromMap(Map<String, Object> map) {
      GAInt fromMapResult = new GAInt();
      Object value = map.get("value");
      fromMapResult.value = (value == null) ? null : ((value instanceof Integer) ? (Integer)value : (Long)value);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class TrackerId {
    private Long trackerId;
    public Long getTrackerId() { return trackerId; }
    public void setTrackerId(Long setterArg) { this.trackerId = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("trackerId", trackerId);
      return toMapResult;
    }
    static TrackerId fromMap(Map<String, Object> map) {
      TrackerId fromMapResult = new TrackerId();
      Object trackerId = map.get("trackerId");
      fromMapResult.trackerId = (trackerId == null) ? null : ((trackerId instanceof Integer) ? (Integer)trackerId : (Long)trackerId);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class TrackingId {
    private String trackingId;
    public String getTrackingId() { return trackingId; }
    public void setTrackingId(String setterArg) { this.trackingId = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("trackingId", trackingId);
      return toMapResult;
    }
    static TrackingId fromMap(Map<String, Object> map) {
      TrackingId fromMapResult = new TrackingId();
      Object trackingId = map.get("trackingId");
      fromMapResult.trackingId = (String)trackingId;
      return fromMapResult;
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface TrackerApi {
    void enableExceptionReporting(TrackerBoolValue arg);
    void setSessionTimeout(TrackerIntValue arg);
    void enableAutoActivityTracking(TrackerBoolValue arg);
    void send(HitBuilderMessage arg);
    TrackerGetValue get(TrackerStringValue arg);
    void set(TrackerSetValue arg);
    void setSampleRate(TrackerDoubleValue arg);
    void setUseSecure(TrackerBoolValue arg);
    void setScreenName(TrackerStringValue arg);
    void setLocation(TrackerStringValue arg);
    void setReferrer(TrackerStringValue arg);
    void setPage(TrackerStringValue arg);
    void setHostname(TrackerStringValue arg);
    void setTitle(TrackerStringValue arg);
    void setLanguage(TrackerStringValue arg);
    void setEncoding(TrackerStringValue arg);
    void setScreenColors(TrackerStringValue arg);
    void setScreenResolution(TrackerSetScreenResolutionValue arg);
    void setViewportSize(TrackerStringValue arg);
    TrackerGetClientIdValue getClientId(TrackerIdValue arg);
    void setClientId(TrackerStringValue arg);
    void setAppName(TrackerStringValue arg);
    void setAppId(TrackerStringValue arg);
    void setAppInstallerId(TrackerStringValue arg);
    void setAppVersion(TrackerStringValue arg);
    void setAnonymizeIp(TrackerBoolValue arg);
    void enableAdvertisingIdCollection(TrackerBoolValue arg);

    /** Sets up an instance of `TrackerApi` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, TrackerApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.enableExceptionReporting", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerBoolValue input = TrackerBoolValue.fromMap((Map<String, Object>)message);
              api.enableExceptionReporting(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setSessionTimeout", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerIntValue input = TrackerIntValue.fromMap((Map<String, Object>)message);
              api.setSessionTimeout(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.enableAutoActivityTracking", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerBoolValue input = TrackerBoolValue.fromMap((Map<String, Object>)message);
              api.enableAutoActivityTracking(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.send", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              HitBuilderMessage input = HitBuilderMessage.fromMap((Map<String, Object>)message);
              api.send(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.get", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerStringValue input = TrackerStringValue.fromMap((Map<String, Object>)message);
              TrackerGetValue output = api.get(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.set", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerSetValue input = TrackerSetValue.fromMap((Map<String, Object>)message);
              api.set(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setSampleRate", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerDoubleValue input = TrackerDoubleValue.fromMap((Map<String, Object>)message);
              api.setSampleRate(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setUseSecure", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerBoolValue input = TrackerBoolValue.fromMap((Map<String, Object>)message);
              api.setUseSecure(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setScreenName", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerStringValue input = TrackerStringValue.fromMap((Map<String, Object>)message);
              api.setScreenName(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setLocation", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerStringValue input = TrackerStringValue.fromMap((Map<String, Object>)message);
              api.setLocation(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setReferrer", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerStringValue input = TrackerStringValue.fromMap((Map<String, Object>)message);
              api.setReferrer(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setPage", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerStringValue input = TrackerStringValue.fromMap((Map<String, Object>)message);
              api.setPage(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setHostname", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerStringValue input = TrackerStringValue.fromMap((Map<String, Object>)message);
              api.setHostname(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setTitle", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerStringValue input = TrackerStringValue.fromMap((Map<String, Object>)message);
              api.setTitle(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setLanguage", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerStringValue input = TrackerStringValue.fromMap((Map<String, Object>)message);
              api.setLanguage(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setEncoding", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerStringValue input = TrackerStringValue.fromMap((Map<String, Object>)message);
              api.setEncoding(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setScreenColors", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerStringValue input = TrackerStringValue.fromMap((Map<String, Object>)message);
              api.setScreenColors(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setScreenResolution", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerSetScreenResolutionValue input = TrackerSetScreenResolutionValue.fromMap((Map<String, Object>)message);
              api.setScreenResolution(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setViewportSize", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerStringValue input = TrackerStringValue.fromMap((Map<String, Object>)message);
              api.setViewportSize(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.getClientId", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerIdValue input = TrackerIdValue.fromMap((Map<String, Object>)message);
              TrackerGetClientIdValue output = api.getClientId(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setClientId", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerStringValue input = TrackerStringValue.fromMap((Map<String, Object>)message);
              api.setClientId(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setAppName", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerStringValue input = TrackerStringValue.fromMap((Map<String, Object>)message);
              api.setAppName(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setAppId", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerStringValue input = TrackerStringValue.fromMap((Map<String, Object>)message);
              api.setAppId(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setAppInstallerId", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerStringValue input = TrackerStringValue.fromMap((Map<String, Object>)message);
              api.setAppInstallerId(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setAppVersion", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerStringValue input = TrackerStringValue.fromMap((Map<String, Object>)message);
              api.setAppVersion(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.setAnonymizeIp", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerBoolValue input = TrackerBoolValue.fromMap((Map<String, Object>)message);
              api.setAnonymizeIp(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.TrackerApi.enableAdvertisingIdCollection", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackerBoolValue input = TrackerBoolValue.fromMap((Map<String, Object>)message);
              api.enableAdvertisingIdCollection(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface GoogleAnalyticsApi {
    void getInstance();
    void setLogLevelVerbose();
    void setDryRun(GABool arg);
    GABool isDryRunEnabled();
    void setAppOptOut(GABool arg);
    GABool getAppOptOut();
    void setLocalDispatchPeriod(GAInt arg);
    TrackerId newTracker(TrackingId arg);

    /** Sets up an instance of `GoogleAnalyticsApi` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, GoogleAnalyticsApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.GoogleAnalyticsApi.getInstance", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              api.getInstance();
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.GoogleAnalyticsApi.setLogLevelVerbose", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              api.setLogLevelVerbose();
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.GoogleAnalyticsApi.setDryRun", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              GABool input = GABool.fromMap((Map<String, Object>)message);
              api.setDryRun(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.GoogleAnalyticsApi.isDryRunEnabled", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              GABool output = api.isDryRunEnabled();
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.GoogleAnalyticsApi.setAppOptOut", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              GABool input = GABool.fromMap((Map<String, Object>)message);
              api.setAppOptOut(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.GoogleAnalyticsApi.getAppOptOut", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              GABool output = api.getAppOptOut();
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.GoogleAnalyticsApi.setLocalDispatchPeriod", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              GAInt input = GAInt.fromMap((Map<String, Object>)message);
              api.setLocalDispatchPeriod(input);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.GoogleAnalyticsApi.newTracker", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              TrackingId input = TrackingId.fromMap((Map<String, Object>)message);
              TrackerId output = api.newTracker(input);
              wrapped.put("result", output.toMap());
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  private static Map<String, Object> wrapError(Throwable exception) {
    Map<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", null);
    return errorMap;
  }
}
